<a href="https://colab.research.google.com/github/menduv/mtg-Jamendo/blob/main/MTG_exploratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/raw_df.csv', index_col = [0])

In [3]:
df.tail()

,track_id,artist_id,album_id,path,duration,tags
55605,1422056,496314,165847,56/1422056.mp3,516.0,genre---soundtrack instrument---computer mood/...
55606,1422057,496314,165847,57/1422057.mp3,374.9,genre---soundtrack instrument---computer mood/...
55607,1422058,496314,165847,58/1422058.mp3,315.8,genre---soundtrack instrument---computer mood/...
55608,1422059,496314,165847,59/1422059.mp3,201.3,genre---soundtrack instrument---computer mood/...
55609,1422060,496314,165847,60/1422060.mp3,336.0,genre---soundtrack instrument---computer mood/...

In [4]:
import re

# Example string
s = 'genre---atmospheric genre---classical genre---contemporary genre---soundtrack instrument---cello instrument---orchestra instrument---piano instrument---violin'

# Extract everything between --- and genre, instrument or mood
result_genre = re.findall(r'e---(.*?)(?: genr| instrument| mood|$)', s)
result_instrument = re.findall(r'ment---(.*?)(?: genre| instru| mood|$)', s)
result_mood = re.findall(r'theme---(.*?)(?: genre| instrument| mood|$)', s)

print(result_genre)
print(result_instrument)
print(result_mood)

['atmospheric', 'classical', 'contemporary', 'soundtrack']
['cello', 'orchestra', 'piano', 'violin']
[]

In [5]:
# Define a function to extract values based on the provided regex pattern
def extract_values(tag_string, category):
    pattern = f'{category}(.*?)(?: gen| instru| mood|$)'
    values = re.findall(pattern, tag_string)
    return ', '.join(values) if values else ''

# Apply the function to each row in the DataFrame
df['genre'] = df['tags'].apply(lambda x: extract_values(x, 're---'))
df['instrument'] = df['tags'].apply(lambda x: extract_values(x, 'ment---'))
df['mood'] = df['tags'].apply(lambda x: extract_values(x, 'theme---'))

In [6]:
df

,track_id,artist_id,album_id,path,duration,tags,genre,instrument,mood
1,214,14,31,14/214.mp3,124.6,genre---punkrock,punkrock,,
2,215,14,31,15/215.mp3,151.4,genre---metal,metal,,
3,216,14,31,16/216.mp3,234.9,genre---metal,metal,,
4,217,14,31,17/217.mp3,127.9,genre---punkrock,punkrock,,
5,218,14,31,18/218.mp3,180.7,genre---punkrock,punkrock,,
...,...,...,...,...,...,...,...,...,...
55605,1422056,496314,165847,56/1422056.mp3,516.0,genre---soundtrack instrument---computer mood/...,soundtrack,computer,"advertising, dramatic, epic, movie"
55606,1422057,496314,165847,57/1422057.mp3,374.9,genre---soundtrack instrument---computer mood/...,soundtrack,computer,"advertising, dramatic, epic, movie"
55607,1422058,496314,165847,58/1422058.mp3,315.8,genre---soundtrack instrument---computer mood/...,soundtrack,computer,"dramatic, epic, movie"
55608,1422059,496314,165847,59/1422059.mp3,201.3,genre---soundtrack instrument---computer mood/...,soundtrack,computer,"advertising, dramatic, epic, movie"
55609,1422060,496314,165847,60/1422060.mp3,336.0,genre---soundtrack instrument---computer mood/...,soundtrack,computer,"advertising, dramatic, epic, movie"

In [7]:
df[14700:14710]

,track_id,artist_id,album_id,path,duration,tags,genre,instrument,mood
14701,381530,351807,48415,30/381530.mp3,189.5,genre---rock,rock,,
14702,381531,351807,48415,31/381531.mp3,216.1,genre---rock,rock,,
14703,381532,351807,48415,32/381532.mp3,346.6,genre---poprock genre---rock,"poprock, rock",,
14704,381533,351807,48415,33/381533.mp3,259.2,genre---dance genre---pop,"dance, pop",,
14705,381705,351811,48430,05/381705.mp3,155.9,genre---reggae genre---rock genre---ska,"reggae, rock, ska",,
14706,381706,351811,48430,06/381706.mp3,173.5,genre---reggae genre---ska,"reggae, ska",,
14707,381707,351811,48430,07/381707.mp3,243.7,genre---reggae genre---ska,"reggae, ska",,
14708,381708,351811,48430,08/381708.mp3,242.8,genre---reggae genre---ska,"reggae, ska",,
14709,381709,351811,48430,09/381709.mp3,233.5,genre---reggae genre---ska,"reggae, ska",,
14710,381858,351846,48489,58/381858.mp3,243.7,genre---electronic genre---pop genre---soundtr...,"electronic, pop, soundtrack","drums, guitar",slow

In [8]:
df_new = df.drop(columns = 'tags', axis = 1)

In [9]:
df_new.to_csv('mtg_cleaned.csv')

In [10]:
df = pd.read_csv('mtg_cleaned.csv', index_col = [0])

In [11]:
df

,track_id,artist_id,album_id,path,duration,genre,instrument,mood
1,214,14,31,14/214.mp3,124.6,punkrock,NaN,NaN
2,215,14,31,15/215.mp3,151.4,metal,NaN,NaN
3,216,14,31,16/216.mp3,234.9,metal,NaN,NaN
4,217,14,31,17/217.mp3,127.9,punkrock,NaN,NaN
5,218,14,31,18/218.mp3,180.7,punkrock,NaN,NaN
...,...,...,...,...,...,...,...,...
55605,1422056,496314,165847,56/1422056.mp3,516.0,soundtrack,computer,"advertising, dramatic, epic, movie"
55606,1422057,496314,165847,57/1422057.mp3,374.9,soundtrack,computer,"advertising, dramatic, epic, movie"
55607,1422058,496314,165847,58/1422058.mp3,315.8,soundtrack,computer,"dramatic, epic, movie"
55608,1422059,496314,165847,59/1422059.mp3,201.3,soundtrack,computer,"advertising, dramatic, epic, movie"
55609,1422060,496314,165847,60/1422060.mp3,336.0,soundtrack,computer,"advertising, dramatic, epic, movie"